// examples/vue/basic-usage.vue
<template>
  <div class="blog-container">
    <header>
      <h1>My Blog</h1>
      <p>Powered by Vibe CMS</p>
    </header>

    <!-- Loading state -->
    <div v-if="loading" class="loading">
      Loading posts...
    </div>

    <!-- Error state -->
    <div v-else-if="error" class="error">
      <p>Error loading posts: {{ error }}</p>
      <button @click="fetchPosts">Retry</button>
    </div>

    <!-- Posts -->
    <main v-else>
      <article v-for="post in posts" :key="post.id" class="post">
        <h2>{{ post.data.title }}</h2>
        <p class="excerpt">{{ post.data.excerpt }}</p>
        <div class="meta">
          <span>Published: {{ formatDate(post.data.published_at) }}</span>
          <span>Author: {{ post.data.author }}</span>
        </div>
      </article>

      <!-- Load more button -->
      <button 
        v-if="posts.length > 0 && !allLoaded" 
        @click="loadMore"
        :disabled="loadingMore"
        class="load-more"
      >
        {{ loadingMore ? 'Loading...' : 'Load More' }}
      </button>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { createVibeCMS, type VibeCMSError } from '@dufourpascal/vibe-cms-sdk'

// Types
interface BlogPost {
  id: string
  data: {
    title: string
    excerpt: string
    content: string
    published_at: string
    author: string
  }
}

// Reactive state
const posts = ref<BlogPost[]>([])
const loading = ref(true)
const loadingMore = ref(false)
const error = ref<string | null>(null)
const allLoaded = ref(false)

// CMS client
const cms = createVibeCMS({
  projectId: 'your-project-id',
  baseUrl: 'https://api.vibe-cms.com',
  cache: {
    enabled: true,
    ttl: 300000, // 5 minutes
    storage: 'localStorage'
  }
})

// Methods
const fetchPosts = async () => {
  try {
    loading.value = true
    error.value = null
    
    const fetchedPosts = await cms.collection<BlogPost>('blog_posts').many({ 
      limit: 10 
    })
    
    posts.value = fetchedPosts || []
    allLoaded.value = (fetchedPosts?.length || 0) < 10
  } catch (err) {
    console.error('Error fetching posts:', err)
    if (err instanceof Error) {
      error.value = err.message
    } else {
      error.value = 'An unknown error occurred'
    }
  } finally {
    loading.value = false
  }
}

const loadMore = async () => {
  try {
    loadingMore.value = true
    
    // In a real app, you'd implement pagination with offset/cursor
    const morePosts = await cms.collection<BlogPost>('blog_posts').many({ 
      limit: 10,
      // offset: posts.value.length // Add offset support to your API
    })
    
    if (morePosts && morePosts.length > 0) {
      posts.value.push(...morePosts)
      allLoaded.value = morePosts.length < 10
    } else {
      allLoaded.value = true
    }
  } catch (err) {
    console.error('Error loading more posts:', err)
  } finally {
    loadingMore.value = false
  }
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

// Lifecycle
onMounted(() => {
  fetchPosts()
})
</script>

<style scoped>
.blog-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

header {
  text-align: center;
  margin-bottom: 3rem;
}

header h1 {
  color: #2c3e50;
  margin-bottom: 0.5rem;
}

header p {
  color: #7f8c8d;
  font-size: 1.1rem;
}

.loading, .error {
  text-align: center;
  padding: 2rem;
}

.error {
  color: #e74c3c;
}

.error button {
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  background: #3498db;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.error button:hover {
  background: #2980b9;
}

.post {
  margin-bottom: 2rem;
  padding-bottom: 2rem;
  border-bottom: 1px solid #ecf0f1;
}

.post:last-child {
  border-bottom: none;
}

.post h2 {
  color: #2c3e50;
  margin-bottom: 0.5rem;
}

.excerpt {
  color: #34495e;
  line-height: 1.6;
  margin-bottom: 1rem;
}

.meta {
  display: flex;
  gap: 1rem;
  color: #7f8c8d;
  font-size: 0.9rem;
}

.load-more {
  display: block;
  margin: 2rem auto;
  padding: 0.75rem 2rem;
  background: #3498db;
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  cursor: pointer;
  transition: background 0.2s;
}

.load-more:hover:not(:disabled) {
  background: #2980b9;
}

.load-more:disabled {
  background: #bdc3c7;
  cursor: not-allowed;
}
</style>

// examples/react/basic-usage.tsx
import React, { useState, useEffect, useCallback } from 'react'
import { createVibeCMS, type VibeCMSError } from '@dufourpascal/vibe-cms-sdk'

// Types
interface BlogPost {
  id: string
  data: {
    title: string
    excerpt: string
    content: string
    published_at: string
    author: string
  }
}

// CMS client (initialize outside component to avoid recreation)
const cms = createVibeCMS({
  projectId: 'your-project-id',
  baseUrl: 'https://api.vibe-cms.com',
  cache: {
    enabled: true,
    ttl: 300000, // 5 minutes
    storage: 'localStorage'
  }
})

const BlogPosts: React.FC = () => {
  // State
  const [posts, setPosts] = useState<BlogPost[]>([])
  const [loading, setLoading] = useState(true)
  const [loadingMore, setLoadingMore] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [allLoaded, setAllLoaded] = useState(false)

  // Fetch posts
  const fetchPosts = useCallback(async () => {
    try {
      setLoading(true)
      setError(null)
      
      const fetchedPosts = await cms.collection<BlogPost>('blog_posts').many({ 
        limit: 10 
      })
      
      setPosts(fetchedPosts || [])
      setAllLoaded((fetchedPosts?.length || 0) < 10)
    } catch (err) {
      console.error('Error fetching posts:', err)
      if (err instanceof Error) {
        setError(err.message)
      } else {
        setError('An unknown error occurred')
      }
    } finally {
      setLoading(false)
    }
  }, [])

  // Load more posts
  const loadMore = useCallback(async () => {
    try {
      setLoadingMore(true)
      
      // In a real app, you'd implement pagination with offset/cursor
      const morePosts = await cms.collection<BlogPost>('blog_posts').many({ 
        limit: 10,
        // offset: posts.length // Add offset support to your API
      })
      
      if (morePosts && morePosts.length > 0) {
        setPosts(prev => [...prev, ...morePosts])
        setAllLoaded(morePosts.length < 10)
      } else {
        setAllLoaded(true)
      }
    } catch (err) {
      console.error('Error loading more posts:', err)
    } finally {
      setLoadingMore(false)
    }
  }, [posts.length])

  // Format date
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  // Effects
  useEffect(() => {
    fetchPosts()
  }, [fetchPosts])

  // Render loading state
  if (loading) {
    return (
      <div style={styles.container}>
        <div style={styles.loading}>
          Loading posts...
        </div>
      </div>
    )
  }

  // Render error state
  if (error) {
    return (
      <div style={styles.container}>
        <div style={styles.error}>
          <p>Error loading posts: {error}</p>
          <button onClick={fetchPosts} style={styles.retryButton}>
            Retry
          </button>
        </div>
      </div>
    )
  }

  // Render posts
  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>My Blog</h1>
        <p style={styles.subtitle}>Powered by Vibe CMS</p>
      </header>

      <main>
        {posts.map((post) => (
          <article key={post.id} style={styles.post}>
            <h2 style={styles.postTitle}>{post.data.title}</h2>
            <p style={styles.excerpt}>{post.data.excerpt}</p>
            <div style={styles.meta}>
              <span>Published: {formatDate(post.data.published_at)}</span>
              <span>Author: {post.data.author}</span>
            </div>
          </article>
        ))}

        {posts.length > 0 && !allLoaded && (
          <button 
            onClick={loadMore}
            disabled={loadingMore}
            style={{
              ...styles.loadMore,
              ...(loadingMore ? styles.loadMoreDisabled : {})
            }}
          >
            {loadingMore ? 'Loading...' : 'Load More'}
          </button>
        )}
      </main>
    </div>
  )
}

// Styles
const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '2rem',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
  },
  header: {
    textAlign: 'center',
    marginBottom: '3rem'
  },
  title: {
    color: '#2c3e50',
    marginBottom: '0.5rem'
  },
  subtitle: {
    color: '#7f8c8d',
    fontSize: '1.1rem'
  },
  loading: {
    textAlign: 'center',
    padding: '2rem'
  },
  error: {
    textAlign: 'center',
    padding: '2rem',
    color: '#e74c3c'
  },
  retryButton: {
    marginTop: '1rem',
    padding: '0.5rem 1rem',
    background: '#3498db',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer'
  },
  post: {
    marginBottom: '2rem',
    paddingBottom: '2rem',
    borderBottom: '1px solid #ecf0f1'
  },
  postTitle: {
    color: '#2c3e50',
    marginBottom: '0.5rem'
  },
  excerpt: {
    color: '#34495e',
    lineHeight: 1.6,
    marginBottom: '1rem'
  },
  meta: {
    display: 'flex',
    gap: '1rem',
    color: '#7f8c8d',
    fontSize: '0.9rem'
  },
  loadMore: {
    display: 'block',
    margin: '2rem auto',
    padding: '0.75rem 2rem',
    background: '#3498db',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'background 0.2s'
  },
  loadMoreDisabled: {
    background: '#bdc3c7',
    cursor: 'not-allowed'
  }
}

export default BlogPosts
